cassandra:
  image: cassandra
  volumes:
  - ./data:/data
  ports:
    - "9042:9042"

zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"

kafka:
  build: ./kafka-docker/
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock